- name: Create user and add SSH key
  hosts: remote_server
  become: true

  vars:
    ssh_key: "{{ lookup('file', '/path/to/encrypted/key/file') }}"

  tasks:
    - name: Create user
      user:
        name: user1
        createhome: yes

    - name: Add SSH key
      authorized_key:
        user: user1
        key: "{{ ssh_key }}"
